# use base image to setup configuration and artifacts for awesomeAppliction
    FROM perceptivecloud/stack-tomcat7
    ADD . /build
    RUN chmod +x /build/install.sh
    RUN /build/install.sh <%= commit_hash %>
    RUN rm -rf /build 
